spring:
  data:
    redis:
      host: REDIS_HOST
      port: 6379
      password: REDIS_PASSWORD
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://DB_HOST:DB_PORT/DB
    username: DB_USERNAME
    password: DB_PASSWORD
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
jwt:
  secret: JWT_SECRET
  access-token:
    expire-time: ACCESS_TOKEN_EXPIRE_TIME
  refresh-token:
    expire-time: REFRESH_TOKEN_EXPIRE_TIME
google:
  client:
    id: GOOGLE_CLIENT_ID
    secret: GOOGLE_CLIENT_SECRET
  redirect:
    uri: GOOGLE_REDIRECT_URI