name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Create config directory and inject application.yml
        run: |
          mkdir -p config
          echo "${{ secrets.APP_PROPERTIES }}" > config/application.yml

      - name: Create certificates directory and write PKCS12 keystore
        run: |
          mkdir -p certs
          echo "${{ secrets.KEYSTORE_P12_BASE64 }}" | base64 -d > certs/keystore.p12

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --refresh-dependencies

      - name: Build Docker image
        run: |
          docker build \
            --build-arg KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            --build-arg KEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -t apply-server .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_REPO }} -p ${{ secrets.DOCKER_KEY }}
          docker tag apply-server ${{ secrets.DOCKER_REPO }}/apply-server:latest
          docker push ${{ secrets.DOCKER_REPO }}/apply-server

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo docker stop apply-server || true
            sudo docker rm apply-server || true
            sudo docker login -u ${{ secrets.DOCKER_REPO }} -p ${{ secrets.DOCKER_KEY }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}/apply-server:latest
            sudo docker run -d -p 443:443 --net knulikelion --name apply-server \
              -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
              -e KEY_ALIAS=${{ secrets.KEY_ALIAS }} \
              ${{ secrets.DOCKER_REPO }}/apply-server:latest
